// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2LuTVXN3dwuPoQ_YTCaA74yGMNQyeXE',
    appId: '1:394138245821:web:3660372da6f9735d7235d4',
    messagingSenderId: '394138245821',
    projectId: 'stocks-designli',
    authDomain: 'stocks-designli.firebaseapp.com',
    storageBucket: 'stocks-designli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjnbkxPtBnCbSVs7ZlAtqWc7AkfpMBvg',
    appId: '1:394138245821:android:f7801a499e12110e7235d4',
    messagingSenderId: '394138245821',
    projectId: 'stocks-designli',
    storageBucket: 'stocks-designli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIoeSXg2vs9R_KRVW5g_j6IX4rMVtpChQ',
    appId: '1:394138245821:ios:1183211feba7efda7235d4',
    messagingSenderId: '394138245821',
    projectId: 'stocks-designli',
    storageBucket: 'stocks-designli.appspot.com',
    iosBundleId: 'com.example.stockTestDesignli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIoeSXg2vs9R_KRVW5g_j6IX4rMVtpChQ',
    appId: '1:394138245821:ios:98ce756cc8d5c1577235d4',
    messagingSenderId: '394138245821',
    projectId: 'stocks-designli',
    storageBucket: 'stocks-designli.appspot.com',
    iosBundleId: 'com.example.stockTestDesignli.RunnerTests',
  );
}
